package com.ruijie.rcos.rcdc.rco.module.def.api.enums;

/**
 * 
 * Description: Function Description
 * Copyright: Copyright (c) 2018
 * Company: Ruijie Co., Ltd.
 * Create Time: 2019年7月25日
 * 
 * @author wanmulin
 */
public enum ConfigKeyEnum {

    BIGSCREEN_RESOURCE_OVERVIEW_REFRESH_INTERVEL,
    BIGSCREEN_SERVER_OVERVIEW_REFRESH_INTERVEL,
    BIGSCREEN_DESKTOP_OVERVIEW_REFRESH_INTERVEL,
    BIGSCREEN_NORMAL_DISTRIBUTION_REFRESH_INTERVEL,
    BIGSCREEN_SERVER_FORECAST_REFRESH_INTERVEL,
    BIGSCREEN_ALARM_REFRESH_INTERVEL,
    BIGSCREEN_SERVER_FORECAST_LIMIT_CPU,
    BIGSCREEN_SERVER_FORECAST_LIMIT_MEMORY,
    BIGSCREEN_SERVER_FORECAST_LIMIT_DISK,
    BIGSCREEN_SERVER_FORECAST_TIME_CPU,
    BIGSCREEN_SERVER_FORECAST_TIME_MEMORY,
    BIGSCREEN_SERVER_FORECAST_TIME_DISK,
    BIGSCREEN_DESKTOP_WARN_CPU,
    BIGSCREEN_DESKTOP_WARN_MEMORY,
    BIGSCREEN_DESKTOP_WARN_DISK,
    BIGSCREEN_DESKTOP_ALARM_CPU,
    BIGSCREEN_DESKTOP_ALARM_MEMORY,
    BIGSCREEN_DESKTOP_ALARM_DISK

}
