package com.ruijie.rcos.rcdc.rco.module.impl.security.auditfile;

/**
 * 桌面池常量
 * Description: Function Description
 * Copyright: Copyright (c) 2021
 * Company: Ruijie Co., Ltd.
 * Create Time: 2021年12月02日
 *
 * @author linke
 */
public interface AuditFileBusinessKey {

    String RCDC_RCO_AUDIT_FILE_DISABLE = "23200221";

    String RCDC_RCO_AUDIT_FILE_APPLY_SINGLE_FILE_SIZE_LIMIT = "23200222";

    String RCDC_RCO_AUDIT_FILE_APPLY_SINGLE_APPLY_FILE_NUM_LIMIT = "23200223";

    String RCDC_RCO_AUDIT_FILE_APPLY_ONE_DAY_FILE_NUM_LIMIT = "23200224";

    String RCDC_RCO_AUDIT_FILE_APPLY_ONE_DAY_FILE_SIZE_LIMIT = "23200225";

    String RCDC_RCO_AUDIT_FILE_APPLY_ALARM_CONTENT = "23200226";

    String RCDC_RCO_AUDIT_FILE_APPLY_NOT_IN_WORK_TIME = "23200227";

    String RCDC_RCO_AUDIT_FILE_APPLY_ONE_HOUR_FILE_NUM_LIMIT = "23200228";

    String RCDC_RCO_AUDIT_FILE_ALARM_NAME = "rcdc_rco_audit_file_alarm_name";

    String RCDC_RCO_AUDIT_FILE_APPLY_ALARM_LEVEL_ERROR = "rcdc_rco_audit_file_alarm_level_error";

    String RCDC_RCO_AUDIT_FILE_APPLY_ALARM_LEVEL_WARN = "rcdc_rco_audit_file_alarm_level_warn";

    String RCDC_RCO_AUDIT_FILE_APPLY_AUTO_APPROVED = "rcdc_rco_audit_file_apply_auto_approved";

    String RCDC_RCO_AUDIT_FILE_APPLY_STATE_NOT_PENDING_APPROVAL = "23200229";

    String RCDC_RCO_AUDIT_FILE_GLOBAL_CONFIG_WORK_TIME_IS_NULL = "23200230";

    String RCDC_RCO_AUDIT_FILE_APPLY_FILE_NAME_IS_BLANK = "23200231";

    String RCDC_RCO_AUDIT_FILE_APPLY_FILE_MD5_IS_BLANK = "23200232";

    String RCDC_RCO_AUDIT_FILE_APPLY_FILE_MD5_NOT_MATCH = "23200233";

    String RCDC_RCO_AUDIT_FILE_APPLY_FILE_SIZE_ILLEGAL = "23200234";

    String RCDC_RCO_AUDIT_FILE_APPLY_FILE_PAGE_ILLEGAL = "23200235";

    String RCDC_RCO_AUDIT_FILE_NOT_EXIST = "23200238";

    String RCDC_RCO_QUARTZ_AUDIT_FILE_APPLY_INTERVAL_DELETE = "23200236";
    String RCDC_RCO_QUARTZ_AUDIT_FILE_APPLY_INTERVAL_DELETE_SUCCESSFUL = "23200237";
    String RCDC_RCO_AUDIT_FILE_APPLY_STATE_NOT_CANCELLED = "23200239";
    String RCDC_RCO_AUDIT_FILE_DELETE_FAIL = "23200244";
    String RCDC_RCO_AUDIT_FILE_APPLY_PARAM_ILLEGAL = "23200240";
    String RCDC_RCO_AUDIT_FILE_ALARM_INSUFFICIENT_SPACE = "23200241";
    String RCDC_RCO_EXTERNAL_STORAGE_STATE_NOT_AVAILABLE = "23200242";
    String RCDC_RCO_EXTERNAL_STORAGE_CANNOT_BE_EMPTY_ERROR = "23200243";


    String RCDC_RCO_AUDIT_FILE_APPLY_FILE_TEMP_PATH_NOT_FIND = "23200245";
    String RCDC_RCO_AUDIT_FILE_APPLY_FILE_STORAGE_SPACE_NOT_ENOUGH = "23200246";
    String RCDC_RCO_AUDIT_FILE_APPLY_FILE_STORAGE_ERROR = "23200247";
    String RCDC_RCO_AUDIT_FILE_SERVER_INNER_ERROR = "23200248";
    String RCDC_RCO_AUDIT_FILE_RESPONSE_SUCCESS = "rcdc_rco_audit_file_response_success";
    String RCDC_RCO_AUDIT_FILE_APPLY_EXCEED_LIMIT_AUTO_REJECT = "rcdc_rco_audit_file_apply_exceed_limit_auto_reject";
    String RCDC_RCO_AUDIT_FILE_APPLY_FILE_SERVER_ERROR_AUTO_REJECT = "rcdc_rco_audit_file_apply_file_server_error_auto_reject";
    String RCDC_RCO_AUDIT_FILE_APPLY_FILE_LIST_IS_BLANK = "rcdc_rco_audit_file_apply_file_list_is_blank";

    String RCDC_RCO_AUDIT_FILE_FTP_DIR_NO_SPACE = "23200249";
    String RCDC_RCO_AUDIT_FILE_GLOBAL_NOT_OPEN_EXTERNAL_STORAGE = "23200250";
    String RCDC_RCO_AUDIT_FILE_APPLY_STATE_NOT_DISCARD = "23200251";
}
