package com.ruijie.rcos.rcdc.rco.module.impl.userprofile.constant;

/**
 * Description: 国际化业务key
 * Copyright: Copyright (c) 2022
 * Company: Ruijie Co., Ltd.
 * Create Time: 2022/4/11
 *
 * @author WuShengQiang
 */
public interface UserProfileBusinessKey {

    String RCDC_RCO_USER_PROFILE_PATH_GROUP_NOT_EXIST = "23200395";

    String RCDC_RCO_USER_PROFILE_PATH_GROUP_RELATED_PATH_NOT_EMPTY = "23200396";

    String RCDC_RCO_USER_PROFILE_PATH_NOT_EXIST = "23200398";
    String RCDC_RCO_USER_PROFILE_PATH_NAME_DUPLICATION = "23200399";
    String RCDC_RCO_USER_PROFILE_PATH_IS_DEFAULT_NOT_EDIT = "23200400";
    String RCDC_RCO_USER_PROFILE_PATH_IS_SPECIAL_NOT_EDIT = "23200401";

    String RCDC_RCO_USER_PROFILE_STRATEGY_NOT_EXIST = "23200402";

    String RCDC_RCO_USER_PROFILE_STRATEGY_USED = "23200404";

    String RCDC_RCO_USER_PROFILE_HAS_IMPORT_PATH = "23200405";

    String RCDC_RCO_USER_PROFILE_STRATEGY_DELETE_LOG = "rcdc_rco_user_profile_strategy_delete_log";
    String RCDC_RCO_USER_PROFILE_STRATEGY_DELETE_RELATIVE_MANY_IDV_GROUP = "23200412";
    String RCDC_RCO_USER_PROFILE_STRATEGY_DELETE_RELATIVE_IDV_GROUP = "23200413";
    String RCDC_RCO_USER_PROFILE_STRATEGY_DELETE_RELATIVE_MANY_GROUP = "23200414";
    String RCDC_RCO_USER_PROFILE_STRATEGY_DELETE_RELATIVE_GROUP = "23200415";
    String RCDC_RCO_USER_PROFILE_STRATEGY_DELETE_RELATIVE_MANY_USER = "23200416";
    String RCDC_RCO_USER_PROFILE_STRATEGY_DELETE_RELATIVE_USER = "23200417";
    String RCDC_RCO_USER_PROFILE_STRATEGY_DELETE_RELATIVE_DESKTOP_POOL = "23200418";

    String RCDC_RCO_USER_PROFILE_PATH_GROUP_DELETE = "rcdc_rco_user_profile_path_group_delete";
    String RCDC_RCO_USER_PROFILE_PATH_GROUP_NAME_DUPLICATION = "23200397";

    String RCDC_RCO_USER_PROFILE_STRATEGY_REMOVE = "rcdc_rco_user_profile_strategy_remove";
    String RCDC_RCO_PATH_HAS_IMPORT = "23200406";
    String RCDC_RCO_PATH_GROUP_DEFAULT_NAME = "rcdc_rco_path_group_default_name";
    String RCDC_RCO_EXPORT_PATH_DOING = "23200407";
    String RCDC_RCO_EXPORT_PATH_FILE_NOT_EXIST = "23200408";

    String RCDC_RCO_USER_PROFILE_STRATEGY_RELATED_PATH_SIZE = "23200409";
    String RCDC_RCO_USER_PROFILE_STRATEGY_NAME_DUPLICATION = "23200403";

    String RCDC_RCO_USER_PROFILE_STRATEGY_DISABLE_IMAGE_TEMPLATE = "23200410";
    String RCDC_RCO_USER_PROFILE_STRATEGY_DISABLE_DESK_STRATEGY = "23200411";

    String RCDC_RCO_USER_PROFILE_LAST_PATH = "23200419";
    String RCDC_RCO_USER_PROFILE_NOT_EXIST_PATH = "23200420";
    String RCDC_RCO_USER_PROFILE_CHILD_PATH_DELETE = "rcdc_rco_user_profile_child_path_delete";

    String RCDC_RCO_USER_PROFILE_VALIDA_PATH_NUM_OVER = "23200421";
    String RCDC_RCO_USER_PROFILE_VALIDA_PATH_STRATEGY_NUM_OVER = "23200422";
    String RCDC_RCO_USER_PROFILE_VALIDA_NUM_OVER = "23200423";
    String RCDC_RCO_USER_PROFILE_VALIDA_NO_STRATEGY = "23200424";
    String RCDC_RCO_USER_PROFILE_VALIDA_STRATEGY_STORAGE_MUST_PERSONAL = "23200425";
    String RCDC_RCO_USER_PROFILE_VALIDA_STRATEGY_STORAGE_MUST_LOCAL = "23200426";
    String RCDC_RCO_USER_PROFILE_VALIDA_IMAGE_CONFLICT = "23200427";
    String RCDC_RCO_USER_PROFILE_VALIDA_GROUP_NOT_EXIST = "23200428";
    String RCDC_RCO_USER_PROFILE_VALIDA_STRATEGY_STORAGE_MUST_FILE_SERVER = "23201537";
    String RCDC_RCO_USER_PROFILE_VALIDA_DESKTOP_CLOSE = "23201097";

    String RCDC_RCO_USER_PROFILE_NOT_FOUND_DESKTOP = "23200429";
    String RCDC_RCO_USER_PROFILE_PATH_ONLY_SUPPORT_FILE_SERVER = "rcdc_rco_user_profile_path_only_support_file_server";
}